version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - python -c "$(curl -sSL https://pdm-project.org/install-pdm.py)" --version 2.20.0.post1 --path ~/.local/pdm
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH ~/.local/pdm/bin/pdm sync -G docs

sphinx:
  configuration: docs/source/conf.py
