version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=~/.uv sh
    pre_install:
      - ~/.uv/uv export --group docs --no-hashes --format requirements-txt > requirements.txt

sphinx:
  configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements.txt
