name: Lint/Format/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
    - name: Install dependencies
      run: |
        uv venv && uv sync --group dev --group test
    - name: Lint/Format with ruff
      run: |
        uv run ruff check && uv run ruff format --check
    - name: Test with pytest
      run: |
        uv run pytest
